# Generated by Django 4.2 on 2023-04-04 18:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scraper', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='scrapedpage',
            name='url',
            field=models.URLField(),
        ),
    ]
