# Generated by Django 4.2 on 2023-04-04 19:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scraper', '0002_alter_scrapedpage_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='scrapedpage',
            name='status',
            field=models.CharField(choices=[('in_progress', 'In Progress'), ('completed', 'Completed')], default='in_progress', max_length=20),
        ),
    ]
