# Generated by Django 4.2 on 2023-04-04 20:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('scraper', '0003_scrapedpage_status'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='scrapedlink',
            options={'ordering': ['id']},
        ),
    ]
